[WIP] [React]: rewrite news encapsulating logic in Pagination module (todo …
chrmod/cliqz-home pull request #7
Opened 2017-06-28 10:47 UTC by giota-cliqz

…rotation & animation)

2017-06-30 08:38 UTC, giota-cliqz commented
@chrmod Need your help regarding how we can disable animated news on first rendering

2017-07-04 18:52 UTC, chrmod requested changes

2017-07-04 18:52 UTC, chrmod commented on packages/cliqz-home-react/src/Article.js
> +         style={{height: '129px'}}>
please put it on a style object

2017-07-04 18:52 UTC, chrmod commented on packages/cliqz-home-react/src/Article.js
> +         ref="articleRef"
is this ref being used?

2017-07-04 18:52 UTC, chrmod commented on packages/cliqz-home-react/src/News.js
> +                    onChangePage={this.onChangePage}
we should discuss indentation strategy for JSX. Kinda like this one. Wonder what airbnb linter preset will tell about it.

2017-07-04 18:52 UTC, chrmod commented on packages/cliqz-home-react/src/News.js
> +        <div className="acordion" style={{height: "141px"}}
again, style probably should be put on style object

2017-07-04 18:52 UTC, chrmod commented on packages/cliqz-home-react/src/News.js
> +             style={{...styles, opacity: this.state.opacity}}>
that's pretty neat :+1:

2017-07-04 18:52 UTC, chrmod commented on packages/cliqz-home-react/src/Pagination.js
> +Pagination.propTypes = propTypes;
in JSX this could be put on class object with `static` keyword, imho prettier

2017-07-04 18:52 UTC, chrmod commented on packages/cliqz-home-react/src/Pagination.js
> +      return <a key={index} className={"button " + ( (page === pager.currentPage) ? 'active' : '') } onClick={() => this.setPage(page)}></a>
is `key` in use?

2017-07-04 18:52 UTC, chrmod commented on packages/cliqz-home-react/src/Pagination.js
> +      return <a key={index} className={"button " + ( (page === pager.currentPage) ? 'active' : '') } onClick={() => this.setPage(page)}></a>
className is implemented in a way that I would suggest to definitely avoid - too long, too complex syntax for inline dynamic property. need to find a better way to deal with this issue

2017-07-04 18:52 UTC, chrmod commented on packages/cliqz-home-react/src/Pagination.js
> +      return null;
should rather return empty `<div></div>` to maintain document structure.

2017-07-04 18:52 UTC, chrmod commented on packages/cliqz-home-react/src/Pagination.js
> +    clearInterval(this.timer);
clearInterval should probably be called also when component will be removed from dom. not sure what is the lifecycle hook for that in react

2017-07-04 18:52 UTC, chrmod commented on packages/cliqz-home-react/src/Pagination.js
> +  animate(setNextPage) {
`setNextPage` should probably be named more generically, like callback

2017-07-04 18:52 UTC, chrmod commented on packages/cliqz-home-react/src/Pagination.js
> +    const newsItems = pager.pages.map((page, index) => {
page and index are almost the same, we can remove one

2017-07-04 18:52 UTC, chrmod commented on packages/cliqz-home-react/src/Pagination.js
> +    for(var i = 1; i<= totalPages; i++) {
would prefer this kind of implementation `[...Array(totalPages).keys()].map(i => i+1)`

2017-07-04 18:52 UTC, chrmod commented on packages/cliqz-home-react/src/Pagination.js
> +    pager = this.getPager(items.length, page);
I'm not getting this pager object. why cannot we just put the state on the component?

2017-07-04 19:05 UTC, chrmod commented
I've requested changes but going to merge it anyhow. Don't want to stop the process at this moment. Change can be applied later on, anyhow for some I'm not sure how to implement idiomatically - we should discuss.

2017-07-04 19:05 UTC, merged