[WIP] [React]: Speed-dials
chrmod/cliqz-home pull request #8
Opened 2017-06-30 09:30 UTC by giota-cliqz

2017-07-04 19:43 UTC, chrmod requested changes
bunch of stuff to discuss, but over all good job!

2017-07-04 19:43 UTC, chrmod commented on packages/cliqz-home-react/package.json
> +    "react-toggle-display": "^2.2.0",
that is rather a regular, not a dev dependency (same for spanan)

2017-07-04 19:43 UTC, chrmod commented on packages/cliqz-home-react/src/AddSpeedDial.js
> +import React, { Component } from 'react';
would rather a call a component with a noun, not a verb, for example `new-speed-dial-form`

2017-07-04 19:43 UTC, chrmod commented on packages/cliqz-home-react/src/AddSpeedDial.js
> +            <svg width="40px" height="40px" viewBox="0 0 40 40" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink">
shouldn't that be an image tag?

2017-07-04 19:43 UTC, chrmod commented on packages/cliqz-home-react/src/SpeedDialsRow.js
> +      showAddButton: () => {
should we put functions on a state?

2017-07-04 19:43 UTC, chrmod commented on packages/cliqz-home-react/src/SpeedDialsRow.js
> +    cliqz.freshtab.addSpeedDial(dial.url, index).then(() => {
not super sure about it, but those two `addSpeedDial` functions should probably be merged

2017-07-04 19:43 UTC, chrmod commented on packages/cliqz-home-react/src/SpeedDialsRow.js
> +                 onClick={this.closeUndo.bind(this, this.props.type)}>
wonder which patter in nicer, this or `onClick={() => this.closeUndo(this.props.type)}` or rather `onClick={() => this.onClick()}`

the last one is the abbervation of `onClick={this.onClick}`, assuming `onClick` is bound to this - which opens a question if we should use bind in JSX components

2017-07-04 19:43 UTC, chrmod commented on packages/cliqz-home-react/src/SpeedDialsRow.js
> +      this.closeUndo.call(this, 'history');
no need for `call`

2017-07-04 19:43 UTC, chrmod commented on packages/cliqz-home-react/src/SpeedDialsRow.js
> +    cliqz.core.sendTelemetry({
how about putting all telemetry signals in one file (as we did in `dropdown`) to hide their complexity a little bit?

2017-07-04 19:43 UTC, chrmod commented on packages/cliqz-home-react/src/SpeedDialsRow.js
> +    const type = speedDial.custom ? 'custom' : 'history';
`type` could be a getter on `SpeedDial` model

2017-07-04 19:43 UTC, chrmod commented on packages/cliqz-home-react/src/SpeedDialsRow.js
> +    this.state.removedItems.push(dial);
not sure if we should change a state like this. this is probably more idiomatic:
```
this.setState({
  removedItems: [
    ...this.state.removedItems,
    dial,
  ],
});

2017-07-04 19:43 UTC, chrmod commented on packages/cliqz-home-react/src/SpeedDialsRow.js
> +      isCustom: this.props.type === 'custom',
we some times use `isCustom` and sometimes a `type` would be nice if we could clean it up on this occasion

2017-07-04 19:43 UTC, chrmod commented on packages/cliqz-home-react/src/SpeedDial.js
> +  constructor(props) {
no need for constructor is it sets nothing

2017-07-04 19:43 UTC, chrmod commented on packages/cliqz-home-react/src/App.js
> +    this.setState({
how about:
```
this.setState({
  dials: {
    ...this.state.dials,
    [dialType]: this.state.dials.filter(d => d !== dial),
  },
});
```

2017-07-04 19:45 UTC, chrmod commented
@mai-cliqz can you please take a look on this one?

2017-07-05 07:50 UTC, mai-cliqz commented on packages/cliqz-home-react/src/AddSpeedDial.js
> +            <svg width="40px" height="40px" viewBox="0 0 40 40" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink">
We could use svg tag if we want to change the fill or stroke of the image programmatically.

2017-07-05 07:54 UTC, mai-cliqz commented on packages/cliqz-home-react/src/App.js
> +                getSpeedDials={this.getSpeedDials} />
Should we delegate these functions to speed dial component ?

2017-07-05 08:00 UTC, mai-cliqz reviewed
@giota-cliqz So internalization will go to next PR ?

2017-07-05 18:03 UTC, chrmod commented
@mai-cliqz internationalization will come through `chrome.i18n`, which I will implement for out bootstrap addon.

2017-07-05 18:03 UTC, merged

2017-07-05 18:04 UTC, chrmod commented
For sake of tomorrows merging to browser-core it got merged here